version: '3'

services:
  webserver:
    image: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./:/var/local/www
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/local/www
    depends_on:
      - database
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: 192.168.15.23
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_IDEKEY: docker

  database:
    image: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    environment:
      POSTGRES_PASSWORD: 1991
      POSTGRES_USER: vlmdr
      POSTGRES_DB: postgres

volumes:
  postgres-data:
