services:
  app:
    image: php
    command: "php -S 0.0.0.0:8080 -t public"
    ports:
      - 127.0.0.1:8080:8080
    working_dir: /app
    volumes:
      - ./:/app

  postgres:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: 

volumes:
  postgres-data:

